name: Deploy AWS Lambda

on:
  push:
    branches:
      - main 
    paths:
      - 'Lambda/'

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps: 
    - users: actions/checkout@v2

    name: Set Up Python  
    users: actions/setup-python@v2
    width:
      python-version: '3.12'

    -name: Install Dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install -r lambda/requirements.txt -t lambda/

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1

      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    
    - name: Deploy to AWS Lambda

      run:|
        cd lambda
        zip -r lambda.zip .
        aws lambda update-function-code --function-name my-test-cicd-lambda --zip-file fileb://lambda.zip